upspll_simpang_php5/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {
    return view('auth/login');
});

Route::group(['middleware' => ['auth']], function() {
    Route::get('/', 'ms_lokasiController@index');
    
Route::get('/home', 'HomeController@index');
// Route::get('/lokasi', 'lokasiController@index');
// Route::get('/lokasi/cetak_pdf', 'lokasiController@cetak_pdf');


Route::get('/detailSimpang/cetak_pdf/{id}', 'detail_simpangController@cetak_pdf');

Route::resource('msLokasis', 'ms_lokasiController');

Route::resource('detailSimpangs', 'detail_simpangController');

Route::resource('planSimpangs', 'plan_simpangController');

Route::get('/plansimpangadd/{id}', 'plan_simpangController@addsimpang');

Route::resource('scheduleSimpangs', 'schedule_simpangController');

Route::get('/schedulesimpangadd/{id}', 'schedule_simpangController@addsimpang');

Route::get('/detail_simpangController/fetch_data', 'detail_simpangController@fetch_data');

Route::post('/detail_simpangController/update_data', 'detail_simpangController@update_data')->name('detail_simpangController.update_data');
Route::post('/detail_simpangController/delete_data', 'detail_simpangController@delete_data')->name('detail_simpangController.delete_data');


Route::get('/detail_simpangController/fetch_data2', 'detail_simpangController@fetch_data2');

Route::post('/detail_simpangController/update_data2', 'detail_simpangController@update_data2')->name('detail_simpangController.update_data2');
Route::post('/detail_simpangController/delete_data2', 'detail_simpangController@delete_data2')->name('detail_simpangController.delete_data2');


});

      

upspll_simpang_php5/app/Models/plan_simpang.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class plan_simpang
 * @package App\Models
 * @version January 14, 2020, 1:51 am UTC
 *
 * @property integer id_simpang_fk
 * @property integer nomor_plan
 * @property integer cycle_time
 * @property integer offset
 * @property integer a
 * @property integer b
 * @property integer c
 * @property integer d
 * @property integer e
 * @property integer f
 * @property string r_minus
 * @property string r_plus
 * @property string y_minus
 * @property string y_plus
 * @property string z_minus
 * @property string z_plus
 * @property string q_minus
 * @property string q_plus
 */
class plan_simpang extends Model
{
    use SoftDeletes;

    public $table = 'plan_simpang';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'nama_lokasi',
        'nomor_plan',
        'cycle_time',
        'offset',
        'a',
        'b',
        'c',
        'd',
        'e',
        'f',
        'r_minus',
        'r_plus',
        'y_minus',
        'y_plus',
        'z_minus',
        'z_plus',
        'q_minus',
        'q_plus'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'nama_lokasi' => 'string',
        'nomor_plan' => 'integer',
        'cycle_time' => 'integer',
        'offset' => 'integer',
        'a' => 'integer',
        'b' => 'integer',
        'c' => 'integer',
        'd' => 'integer',
        'e' => 'integer',
        'f' => 'integer',
        'r_minus' => 'string',
        'r_plus' => 'string',
        'y_minus' => 'string',
        'y_plus' => 'string',
        'z_minus' => 'string',
        'z_plus' => 'string',
        'q_minus' => 'string',
        'q_plus' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        // 'id_simpang_fk' => 'required',
        'nomor_plan' => 'required'
    ];

    public function detail_simpang(){
        return $this->hasOne('\App\Models\detail_simpang','id','nama_lokasi');
    }
    
}

upspll_simpang_php5/app/Http/Controllers/plan_simpangController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Createplan_simpangRequest;
use App\Http\Requests\Updateplan_simpangRequest;
use App\Repositories\plan_simpangRepository;
use App\Repositories\detail_simpangRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;
use DB;

class plan_simpangController extends AppBaseController
{
    /** @var  plan_simpangRepository */
    private $planSimpangRepository;

    public function __construct(detail_simpangRepository $detailSimpangRepo, plan_simpangRepository $planSimpangRepo)
    {
        $this->detailSimpangRepository = $detailSimpangRepo;
        $this->planSimpangRepository = $planSimpangRepo;
    }

    /**
     * Display a listing of the plan_simpang.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->planSimpangRepository->pushCriteria(new RequestCriteria($request));
        $planSimpangs = $this->planSimpangRepository->all();

        return view('plan_simpangs.index')
            ->with('planSimpangs', $planSimpangs);
    }

    /**
     * Show the form for creating a new plan_simpang.
     *
     * @return Response
     */
    public function create()
    {
        $nama_lokasi = DB::table('detail_simpang')->where('nama_lokasi','=','id');
        
        return view('plan_simpangs.create')->with('planSimpang', $nama_lokasi);
    }

    public function addsimpang($id)
    {
        $nama_lokasi = DB::table('detail_simpang')->where('id','=',$id)->first();
        // dd($nama_lokasi);
        return view('plan_simpangs.create')->with('planSimpang', $nama_lokasi);
    }

    /**
     * Store a newly created plan_simpang in storage.
     *
     * @param Createplan_simpangRequest $request
     *
     * @return Response
     */
    public function store(Createplan_simpangRequest $request)
    {
        $this->detailSimpangRepository->pushCriteria(new RequestCriteria($request));
        $detailSimpangs = $this->detailSimpangRepository->all();

        $input = $request->all();
        // dd($input);
        $this->planSimpangRepository->create($input);
        
        if (isset($input['nama_lokasi_arr'])) {
            if(count($input['nama_lokasi_arr'])>0){

                foreach ($input['nama_lokasi_arr'] as $key => $value) {
               
                    $planSimpang = $this->planSimpangRepository->create([
                        'nama_lokasi' => $input['nama_lokasi_arr'][$key],
                        'nomor_plan' => $input['nomor_plan_arr'][$key],
                        'cycle_time' => $input['cycle_time_arr'][$key],
                        'offset' => $input['offset_arr'][$key],
                        'a' => $input['a_arr'][$key],
                        'b' => $input['b_arr'][$key],
                        'c' => $input['c_arr'][$key],
                        'd' => $input['d_arr'][$key],
                        'e' => $input['e_arr'][$key],
                        'f' => $input['f_arr'][$key],
                        'r_minus' => $input['r_minus_arr'][$key],
                        'r_plus' => $input['r_plus_arr'][$key],
                        'y_minus' => $input['y_minus_arr'][$key],
                        'y_plus' => $input['y_plus_arr'][$key],
                        'z_minus' => $input['z_minus_arr'][$key],
                        'z_plus' => $input['z_plus_arr'][$key],
                        'q_minus' => $input['q_minus_arr'][$key],
                        'q_plus' => $input['q_plus_arr'][$key],
                    ]);
                }
        }
        }
            
        Flash::success('Plan Simpang saved successfully.');

        return view('detail_simpangs.index')
            ->with('detailSimpangs', $detailSimpangs);
    }

    /**
     * Display the specified plan_simpang.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $planSimpang = $this->planSimpangRepository->findWithoutFail($id);

        if (empty($planSimpang)) {
            Flash::error('Plan Simpang not found');

            return redirect(route('planSimpangs.index'));
        }

        return view('plan_simpangs.show')->with('planSimpang', $planSimpang);
    }

    /**
     * Show the form for editing the specified plan_simpang.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $nama_lokasi = DB::table('detail_simpang')->where('nama_lokasi','=',$id);
        
        return view('plan_simpangs.edit')->with('planSimpang', $nama_lokasi);
    }

    /**
     * Update the specified plan_simpang in storage.
     *
     * @param  int              $id
     * @param Updateplan_simpangRequest $request
     *
     * @return Response
     */
    public function update($id, Updateplan_simpangRequest $request)
    {
        $planSimpang = $this->planSimpangRepository->findWithoutFail($id);

        if (empty($planSimpang)) {
            Flash::error('Plan Simpang not found');

            return redirect(route('planSimpangs.index'));
        }

        $planSimpang = $this->planSimpangRepository->update($request->all(), $id);

        Flash::success('Plan Simpang updated successfully.');

        return redirect(route('planSimpangs.index'));
    }

    /**
     * Remove the specified plan_simpang from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $planSimpang = $this->planSimpangRepository->findWithoutFail($id);

        if (empty($planSimpang)) {
            Flash::error('Plan Simpang not found');

            return redirect(route('planSimpangs.index'));
        }

        $this->planSimpangRepository->delete($id);

        Flash::success('Plan Simpang deleted successfully.');

        return redirect(route('planSimpangs.index'));
    }
}

upspll_simpang_php5/resources/views/plan_simpangs/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Plan Simpang
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'planSimpangs.store']) !!}

                        @include('plan_simpangs.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

upspll_simpang_php5/resources/views/plan_simpangs/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Plan Simpang
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($planSimpang, ['route' => ['planSimpangs.update', $planSimpang->id], 'method' => 'patch']) !!}

                        @include('plan_simpangs.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

upspll_simpang_php5/resources/views/plan_simpangs/fields.blade.php
<!-- Id Simpang Fk Field -->
<div class="form-group col-sm-12">
    {!! Form::label('nama_lokasi', 'Nama Lokasi:') !!}
    {!! Form::hidden('nama_lokasi', $planSimpang->nama_lokasi) !!}
    <p>{!! Form::label('nama_lokasi2', $planSimpang->nama_lokasi, ['disabled'=>'true']) !!}</p>
</div>

<!-- Nomor Plan Field -->
<div class="form-group col-sm-2">
    {!! Form::label('nomor_plan', 'Nomor Plan:') !!}
    {!! Form::number('nomor_plan', null, ['class' => 'form-control']) !!}
</div>

<!-- Cycle Time Field -->
<div class="form-group col-sm-2">
    {!! Form::label('cycle_time', 'Cycle Time:') !!}
    {!! Form::number('cycle_time', null, ['class' => 'form-control']) !!}
</div>

<!-- Offset Field -->
<div class="form-group col-sm-2">
    {!! Form::label('offset', 'Offset:') !!}
    {!! Form::number('offset', null, ['class' => 'form-control']) !!}
</div>

<!-- A Field -->
<div class="form-group col-sm-2">
    {!! Form::label('a', 'A:') !!}
    {!! Form::number('a', null, ['class' => 'form-control']) !!}
</div>

<!-- B Field -->
<div class="form-group col-sm-2">
    {!! Form::label('b', 'B:') !!}
    {!! Form::number('b', null, ['class' => 'form-control']) !!}
</div>

<!-- C Field -->
<div class="form-group col-sm-2">
    {!! Form::label('c', 'C:') !!}
    {!! Form::number('c', null, ['class' => 'form-control']) !!}
</div>

<!-- D Field -->
<div class="form-group col-sm-2">
    {!! Form::label('d', 'D:') !!}
    {!! Form::number('d', null, ['class' => 'form-control']) !!}
</div>

<!-- E Field -->
<div class="form-group col-sm-2">
    {!! Form::label('e', 'E:') !!}
    {!! Form::number('e', null, ['class' => 'form-control']) !!}
</div>

<!-- F Field -->
<div class="form-group col-sm-2">
    {!! Form::label('f', 'F:') !!}
    {!! Form::number('f', null, ['class' => 'form-control']) !!}
</div>

<!-- R Minus Field -->
<div class="form-group col-sm-2">
    {!! Form::label('r_minus', 'R-:') !!}
    {!! Form::text('r_minus', null, ['class' => 'form-control']) !!}
</div>

<!-- R Plus Field -->
<div class="form-group col-sm-2">
    {!! Form::label('r_plus', 'R+:') !!}
    {!! Form::text('r_plus', null, ['class' => 'form-control']) !!}
</div>

<!-- Y Minus Field -->
<div class="form-group col-sm-2">
    {!! Form::label('y_minus', 'Y-:') !!}
    {!! Form::text('y_minus', null, ['class' => 'form-control']) !!}
</div>

<!-- Y Plus Field -->
<div class="form-group col-sm-2">
    {!! Form::label('y_plus', 'Y+:') !!}
    {!! Form::text('y_plus', null, ['class' => 'form-control']) !!}
</div>

<!-- Z Minus Field -->
<div class="form-group col-sm-2">
    {!! Form::label('z_minus', 'Z-:') !!}
    {!! Form::text('z_minus', null, ['class' => 'form-control']) !!}
</div>

<!-- Z Plus Field -->
<div class="form-group col-sm-2">
    {!! Form::label('z_plus', 'Z+:') !!}
    {!! Form::text('z_plus', null, ['class' => 'form-control']) !!}
</div>

<!-- Q Minus Field -->
<div class="form-group col-sm-2">
    {!! Form::label('q_minus', 'Q-:') !!}
    {!! Form::text('q_minus', null, ['class' => 'form-control']) !!}
</div>

<!-- Q Plus Field -->
<div class="form-group col-sm-2">
    {!! Form::label('q_plus', 'Q+:') !!}
    {!! Form::text('q_plus', null, ['class' => 'form-control']) !!}
</div>

<div id="mydiv"></div>

<div class="form-group col-sm-4">
    <input type="button" class="uk-button uk-button-default uk-button-small" value="tambah plan" onclick="createNew()" />
</div>
<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'uk-button uk-button-primary uk-button uk-button-small']) !!}
    <a href="{{ route('detailSimpangs.index') }}" class="uk-button uk-button-default uk-button-small">Cancel</a>
</div>


<script>
    var i = 2;

    function createNew() {
        $("#mydiv").append('<div class="col-sm-12" style="border-top: 3px solid #3c8dbc;padding-bottom:10px;width:99%;margin-left:5px; ">'+'</div>' + '<div class="form-group col-sm-2">' +'<label>'+'Nomor Plan :'+'</label>'+
            '<input type="number" name="nomor_plan_arr[]" class="form-control" placeholder=""/>' +
            '</div>' + '<div class="form-group col-sm-2">' +'<label>'+'Cycle Time:'+'</label>'+
            '<input type="number" name="cycle_time_arr[]" class="form-control" placeholder=""/>' +
            '</div>' + '<div class="form-group  col-sm-2">' + '<label>'+'Offset:'+'</label>'+
            '<input type="number" name="offset_arr[]" class="form-control" placeholder=""/>' + '</div>' +
            '<div class="form-group  col-sm-2">' +'<label>'+'A :'+'</label>'+
            '<input type="number" name="a_arr[]" class="form-control" placeholder=""/>' + '</div>' +
            '<div class="form-group  col-sm-2">' +'<label>'+'B :'+'</label>'+
            '<input type="number" name="b_arr[]" class="form-control" placeholder=""/>' + '</div>' +
            '<div class="form-group  col-sm-2">' +'<label>'+'C :'+'</label>'+
            '<input type="number" name="c_arr[]" class="form-control" placeholder=""/>' + '</div>' +
            '<div class="form-group  col-sm-2">' +'<label>'+'D :'+'</label>'+
            '<input type="number" name="d_arr[]" class="form-control" placeholder=""/>' + '</div>' +
            '<div class="form-group  col-sm-2">' +'<label>'+'E :'+'</label>'+
            '<input type="number" name="e_arr[]" class="form-control" placeholder=""/>' + '</div>' +
            '<div class="form-group  col-sm-2">' +'<label>'+'F :'+'</label>'+
            '<input type="number" name="f_arr[]" class="form-control" placeholder=""/>' + '</div>' +
            '<div class="form-group  col-sm-2">' +'<label>'+'R- :'+'</label>'+
            '<input type="text" name="r_minus_arr[]" class="form-control" placeholder=""/>' + '</div>' +
            '<div class="form-group  col-sm-2">' +'<label>'+'R+ :'+'</label>'+
            '<input type="text" name="r_plus_arr[]" class="form-control" placeholder=""/>' + '</div>' +
            '<div class="form-group  col-sm-2">' +'<label>'+'Y- :'+'</label>'+
            '<input type="text" name="y_minus_arr[]" class="form-control" placeholder=""/>' + '</div>' +
            '<div class="form-group  col-sm-2">' +'<label>'+'Y+ :'+'</label>'+
            '<input type="text" name="y_plus_arr[]" class="form-control" placeholder=""/>' + '</div>' +
            '<div class="form-group  col-sm-2">' +'<label>'+'Z- :'+'</label>'+
            '<input type="text" name="z_minus_arr[]" class="form-control" placeholder=""/>' + '</div>' +
            '<div class="form-group  col-sm-2">' +'<label>'+'Z+ :'+'</label>'+
            '<input type="text" name="z_plus_arr[]" class="form-control" placeholder=""/>' + '</div>' +
            '<div class="form-group  col-sm-2">' +'<label>'+'Q- :'+'</label>'+
            '<input type="text" name="q_minus_arr[]" class="form-control" placeholder=""/>' + '</div>' +
            '<div class="form-group  col-sm-2">' +'<label>'+'Q+ :'+'</label>'+
            '<input type="text" name="q_plus_arr[]" class="form-control" placeholder=""/>' + '</div>' +
            '<br/>'+
            '<div class="form-group col-sm-2">' +
            '<input type="hidden" name="nama_lokasi_arr[]" class="form-control" placeholder="" value="{!!$planSimpang->nama_lokasi!!}"/>' +
            '</div>');
        i++;
    }

</script>

upspll_simpang_php5/resources/views/plan_simpangs/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Plan Simpangs</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('planSimpangs.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('plan_simpangs.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

upspll_simpang_php5/resources/views/plan_simpangs/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Plan Simpang
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('plan_simpangs.show_fields')
                    <a href="{!! route('planSimpangs.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

upspll_simpang_php5/resources/views/plan_simpangs/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $planSimpang->id !!}</p>
</div>

<!-- Nama Lokasi Field -->
<div class="form-group">
    {!! Form::label('nama_lokasi', 'Nama Lokasi:') !!}
    <p>{!! $planSimpang->nama_lokasi !!}</p>
</div>

<!-- Nomor Plan Field -->
<div class="form-group">
    {!! Form::label('nomor_plan', 'Nomor Plan:') !!}
    <p>{!! $planSimpang->nomor_plan !!}</p>
</div>

<!-- Cycle Time Field -->
<div class="form-group">
    {!! Form::label('cycle_time', 'Cycle Time:') !!}
    <p>{!! $planSimpang->cycle_time !!}</p>
</div>

<!-- Offset Field -->
<div class="form-group">
    {!! Form::label('offset', 'Offset:') !!}
    <p>{!! $planSimpang->offset !!}</p>
</div>

<!-- A Field -->
<div class="form-group">
    {!! Form::label('a', 'A:') !!}
    <p>{!! $planSimpang->a !!}</p>
</div>

<!-- B Field -->
<div class="form-group">
    {!! Form::label('b', 'B:') !!}
    <p>{!! $planSimpang->b !!}</p>
</div>

<!-- C Field -->
<div class="form-group">
    {!! Form::label('c', 'C:') !!}
    <p>{!! $planSimpang->c !!}</p>
</div>

<!-- D Field -->
<div class="form-group">
    {!! Form::label('d', 'D:') !!}
    <p>{!! $planSimpang->d !!}</p>
</div>

<!-- E Field -->
<div class="form-group">
    {!! Form::label('e', 'E:') !!}
    <p>{!! $planSimpang->e !!}</p>
</div>

<!-- F Field -->
<div class="form-group">
    {!! Form::label('f', 'F:') !!}
    <p>{!! $planSimpang->f !!}</p>
</div>

<!-- R Minus Field -->
<div class="form-group">
    {!! Form::label('r_minus', 'R Minus:') !!}
    <p>{!! $planSimpang->r_minus !!}</p>
</div>

<!-- R Plus Field -->
<div class="form-group">
    {!! Form::label('r_plus', 'R Plus:') !!}
    <p>{!! $planSimpang->r_plus !!}</p>
</div>

<!-- Y Minus Field -->
<div class="form-group">
    {!! Form::label('y_minus', 'Y Minus:') !!}
    <p>{!! $planSimpang->y_minus !!}</p>
</div>

<!-- Y Plus Field -->
<div class="form-group">
    {!! Form::label('y_plus', 'Y Plus:') !!}
    <p>{!! $planSimpang->y_plus !!}</p>
</div>

<!-- Z Minus Field -->
<div class="form-group">
    {!! Form::label('z_minus', 'Z Minus:') !!}
    <p>{!! $planSimpang->z_minus !!}</p>
</div>

<!-- Z Plus Field -->
<div class="form-group">
    {!! Form::label('z_plus', 'Z Plus:') !!}
    <p>{!! $planSimpang->z_plus !!}</p>
</div>

<!-- Q Minus Field -->
<div class="form-group">
    {!! Form::label('q_minus', 'Q Minus:') !!}
    <p>{!! $planSimpang->q_minus !!}</p>
</div>

<!-- Q Plus Field -->
<div class="form-group">
    {!! Form::label('q_plus', 'Q Plus:') !!}
    <p>{!! $planSimpang->q_plus !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $planSimpang->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $planSimpang->updated_at !!}</p>
</div>

<!-- Deleted At Field -->
<div class="form-group">
    {!! Form::label('deleted_at', 'Deleted At:') !!}
    <p>{!! $planSimpang->deleted_at !!}</p>
</div>

upspll_simpang_php5/resources/views/plan_simpangs/table.blade.php
<table class="table table-responsive" id="planSimpangs-table">
    <thead>
        <tr>
            <th>Nama Lokasi</th>
        <th>Nomor Plan</th>
        <th>Cycle Time</th>
        <th>Offset</th>
        <th>A</th>
        <th>B</th>
        <th>C</th>
        <th>D</th>
        <th>E</th>
        <th>F</th>
        <th>R Minus</th>
        <th>R Plus</th>
        <th>Y Minus</th>
        <th>Y Plus</th>
        <th>Z Minus</th>
        <th>Z Plus</th>
        <th>Q Minus</th>
        <th>Q Plus</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($planSimpangs as $planSimpang)
        <tr>
            <td>{!! $planSimpang->nama_lokasi !!}</td>
            <td>{!! $planSimpang->nomor_plan !!}</td>
            <td>{!! $planSimpang->cycle_time !!}</td>
            <td>{!! $planSimpang->offset !!}</td>
            <td>{!! $planSimpang->a !!}</td>
            <td>{!! $planSimpang->b !!}</td>
            <td>{!! $planSimpang->c !!}</td>
            <td>{!! $planSimpang->d !!}</td>
            <td>{!! $planSimpang->e !!}</td>
            <td>{!! $planSimpang->f !!}</td>
            <td>{!! $planSimpang->r_minus !!}</td>
            <td>{!! $planSimpang->r_plus !!}</td>
            <td>{!! $planSimpang->y_minus !!}</td>
            <td>{!! $planSimpang->y_plus !!}</td>
            <td>{!! $planSimpang->z_minus !!}</td>
            <td>{!! $planSimpang->z_plus !!}</td>
            <td>{!! $planSimpang->q_minus !!}</td>
            <td>{!! $planSimpang->q_plus !!}</td>
            <td>
                {!! Form::open(['route' => ['planSimpangs.destroy', $planSimpang->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('planSimpangs.show', [$planSimpang->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('planSimpangs.edit', [$planSimpang->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>