upspll_simpang_php5/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {
    return view('auth/login');
});

Route::group(['middleware' => ['auth']], function() {
    Route::get('/', 'ms_lokasiController@index');
    
Route::get('/home', 'HomeController@index');
// Route::get('/lokasi', 'lokasiController@index');
// Route::get('/lokasi/cetak_pdf', 'lokasiController@cetak_pdf');


Route::get('/detailSimpang/cetak_pdf/{id}', 'detail_simpangController@cetak_pdf');

Route::resource('msLokasis', 'ms_lokasiController');

Route::resource('detailSimpangs', 'detail_simpangController');

Route::resource('planSimpangs', 'plan_simpangController');

Route::get('/plansimpangadd/{id}', 'plan_simpangController@addsimpang');

Route::resource('scheduleSimpangs', 'schedule_simpangController');

Route::get('/schedulesimpangadd/{id}', 'schedule_simpangController@addsimpang');

Route::get('/detail_simpangController/fetch_data', 'detail_simpangController@fetch_data');

Route::post('/detail_simpangController/update_data', 'detail_simpangController@update_data')->name('detail_simpangController.update_data');
Route::post('/detail_simpangController/delete_data', 'detail_simpangController@delete_data')->name('detail_simpangController.delete_data');


Route::get('/detail_simpangController/fetch_data2', 'detail_simpangController@fetch_data2');

Route::post('/detail_simpangController/update_data2', 'detail_simpangController@update_data2')->name('detail_simpangController.update_data2');
Route::post('/detail_simpangController/delete_data2', 'detail_simpangController@delete_data2')->name('detail_simpangController.delete_data2');


});

      

upspll_simpang_php5/app/Models/schedule_simpang.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class schedule_simpang
 * @package App\Models
 * @version January 16, 2020, 2:19 am UTC
 *
 * @property string nama_lokasi
 * @property integer nomor_plan
 * @property integer ct
 * @property time time
 * @property string days
 */
class schedule_simpang extends Model
{
    use SoftDeletes;

    public $table = 'schedule_simpang';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'nama_lokasi',
        'nomor_plan',
        'ct',
        'time',
        'days'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'nama_lokasi' => 'string',
        'nomor_plan' => 'integer',
        'ct' => 'integer',
        'days' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    public function detail_simpang(){
        return $this->hasOne('\App\Models\detail_simpang','id','nama_lokasi');
    }
}

upspll_simpang_php5/app/Http/Controllers/schedule_simpangController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Createschedule_simpangRequest;
use App\Http\Requests\Updateschedule_simpangRequest;
use App\Repositories\schedule_simpangRepository;
use App\Repositories\detail_simpangRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;
use DB;

class schedule_simpangController extends AppBaseController
{
    /** @var  schedule_simpangRepository */
    private $scheduleSimpangRepository;

    public function __construct(detail_simpangRepository $detailSimpangRepo, schedule_simpangRepository $scheduleSimpangRepo)
    {
        
        $this->detailSimpangRepository = $detailSimpangRepo;
        $this->scheduleSimpangRepository = $scheduleSimpangRepo;
    }

    /**
     * Display a listing of the schedule_simpang.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->scheduleSimpangRepository->pushCriteria(new RequestCriteria($request));
        $scheduleSimpangs = $this->scheduleSimpangRepository->all();

        return view('schedule_simpangs.index')
            ->with('scheduleSimpangs', $scheduleSimpangs);
    }

    /**
     * Show the form for creating a new schedule_simpang.
     *
     * @return Response
     */
    public function create()
    {
        $nama_lokasi = DB::table('detail_simpang')->where('nama_lokasi','=','id');

        return view('schedule_simpangs.create')->with('scheduleSimpang', $nama_lokasi);
    }

    public function addsimpang($id)
    {
        $nama_lokasi = DB::table('detail_simpang')->where('id','=',$id)->first();
        return view('schedule_simpangs.create')->with('scheduleSimpang', $nama_lokasi);
    }

    /**
     * Store a newly created schedule_simpang in storage.
     *
     * @param Createschedule_simpangRequest $request
     *
     * @return Response
     */
    public function store(Createschedule_simpangRequest $request)
    {
        $this->detailSimpangRepository->pushCriteria(new RequestCriteria($request));
        $detailSimpangs = $this->detailSimpangRepository->all();

        $input = $request->all();
        // dd($input);
        $this->scheduleSimpangRepository->create($input);

        if (isset($input['nama_lokasi_arr'])) {
            if(count($input['nama_lokasi_arr'])>0){

                foreach ($input['nama_lokasi_arr'] as $key => $value) {
               
                    $scheduleSimpangs  = $this->scheduleSimpangRepository->create([
                        'nama_lokasi' => $input['nama_lokasi_arr'][$key],
                        'nomor_plan' => $input['nomor_plan_arr'][$key],
                        'ct' => $input['ct_arr'][$key],
                        'time' => $input['time_arr'][$key],
                        'days' => $input['days_arr'][$key],
                    ]);
                }
        }
        }

        Flash::success('Schedule Simpang saved successfully.');

        return view('detail_simpangs.index')
            ->with('detailSimpangs', $detailSimpangs);
    }

    /**
     * Display the specified schedule_simpang.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $scheduleSimpang = $this->scheduleSimpangRepository->findWithoutFail($id);

        if (empty($scheduleSimpang)) {
            Flash::error('Schedule Simpang not found');

            return redirect(route('scheduleSimpangs.index'));
        }

        return view('schedule_simpangs.show')->with('scheduleSimpang', $scheduleSimpang);
    }

    /**
     * Show the form for editing the specified schedule_simpang.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $scheduleSimpang = $this->scheduleSimpangRepository->findWithoutFail($id);

        if (empty($scheduleSimpang)) {
            Flash::error('Schedule Simpang not found');

            return redirect(route('scheduleSimpangs.index'));
        }

        return view('schedule_simpangs.edit')->with('scheduleSimpang', $scheduleSimpang);
    }

    /**
     * Update the specified schedule_simpang in storage.
     *
     * @param  int              $id
     * @param Updateschedule_simpangRequest $request
     *
     * @return Response
     */
    public function update($id, Updateschedule_simpangRequest $request)
    {
        $scheduleSimpang = $this->scheduleSimpangRepository->findWithoutFail($id);

        if (empty($scheduleSimpang)) {
            Flash::error('Schedule Simpang not found');

            return redirect(route('scheduleSimpangs.index'));
        }

        $scheduleSimpang = $this->scheduleSimpangRepository->update($request->all(), $id);

        Flash::success('Schedule Simpang updated successfully.');

        return redirect(route('scheduleSimpangs.index'));
    }

    /**
     * Remove the specified schedule_simpang from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $scheduleSimpang = $this->scheduleSimpangRepository->findWithoutFail($id);

        if (empty($scheduleSimpang)) {
            Flash::error('Schedule Simpang not found');

            return redirect(route('scheduleSimpangs.index'));
        }

        $this->scheduleSimpangRepository->delete($id);

        Flash::success('Schedule Simpang deleted successfully.');

        return redirect(route('scheduleSimpangs.index'));
    }
}

upspll_simpang_php5/resources/views/schedule_simpangs/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Schedule Simpang
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'scheduleSimpangs.store']) !!}

                        @include('schedule_simpangs.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

upspll_simpang_php5/resources/views/schedule_simpangs/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Schedule Simpang
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($scheduleSimpang, ['route' => ['scheduleSimpangs.update', $scheduleSimpang->id], 'method' => 'patch']) !!}

                        @include('schedule_simpangs.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

upspll_simpang_php5/resources/views/schedule_simpangs/fields.blade.php
<!-- Nama Lokasi Field -->
<div class="form-group col-sm-12">
    {!! Form::label('nama_lokasi', 'Nama Lokasi:') !!}
    {!! Form::hidden('nama_lokasi', $scheduleSimpang->nama_lokasi, ['class' => 'form-control']) !!}
    <p>{!! Form::label('nama_lokasi2', $scheduleSimpang->nama_lokasi, ['disabled'=>'true']) !!}</p>
</div>

<!-- Nomor Plan Field -->
<div class="form-group col-sm-6">
    {!! Form::label('nomor_plan', 'Nomor Plan:') !!}
    {!! Form::number('nomor_plan', null, ['class' => 'form-control']) !!}
</div>

<!-- Ct Field -->
<div class="form-group col-sm-6">
    {!! Form::label('ct', 'Ct:') !!}
    {!! Form::number('ct', null, ['class' => 'form-control']) !!}
</div>

<!-- Time Field -->
<div class="form-group col-sm-6">
    {!! Form::label('time', 'Time:') !!}
    {!! Form::time('time', null, ['class' => 'form-control']) !!}
</div>

<!-- Days Field -->
<div class="form-group has-feedback{{ $errors->has('days') ? ' has-error' : '' }} col-sm-6">
{!! Form::label('days', 'days :') !!}
            <select class="form-control" name="days"  value="{{ old('days') }}" >
                <option value="">----pilih hari----</option>
                <option value="Every Day">Every Day</option>
                <option value="Monday to Friday">Monday to Friday</option>
                <option value="Saturday to Sunday">Saturday to Sunday</option>
                <option value="End of Schedule">End of Schedule</option>
            </select>
            </div>

<div id="mydiv"></div>

<div class="form-group col-sm-12">
    <input type="button" class="uk-button uk-button-default uk-button-small" value="tambah schedule" onclick="createNew()" />
</div>
<script>
    var i = 2;

    function createNew() {
        $("#mydiv").append('<div class="col-sm-12" style="border-top: 3px solid #3c8dbc;padding-bottom:10px;width:99%;margin-left:5px; ">'+'</div>' +
            '</div>' + '<div class="form-group col-sm-6">' +'<label>'+'Nomor Plan :'+'</label>'+
            '<input type="number" name="nomor_plan_arr[]" class="form-control" placeholder=""/>' +
            '</div>' + '<div class="form-group col-sm-6">' +'<label>'+'CT:'+'</label>'+
            '<input type="number" name="ct_arr[]" class="form-control" placeholder=""/>' +
            '</div>' + '<div class="form-group  col-sm-6">' + '<label>'+'time:'+'</label>'+
            '<input type="TIME" name="time_arr[]" class="form-control" placeholder=""/>' + '</div>' +
            '<div class="form-group col-sm-6">'+'<label>'+'days :'+'</label>'+
            '<select class="form-control" name="days_arr[]"'+
            '<option value="">----pilih hari----</option>'+
            '<option value="Every Day">Every Day</option>'+
            '<option value="Monday to Friday">Monday to Friday</option>'+
            '<option value="Saturday to Sunday">Saturday to Sunday</option>'+
            '<option value="End of Schedule">End of Schedule</option>'+
            '</select>'+'</div>'+
            '<input type="hidden" name="nama_lokasi_arr[]" class="form-control" placeholder="" value="{!!$scheduleSimpang->nama_lokasi!!}" />'+
            '<br/>');
        i++;
    }

</script>



<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'uk-button uk-button-primary uk-button-small']) !!}
    <a href="{!! route('detailSimpangs.index') !!}" class="uk-button uk-button-default uk-button-small">Cancel</a>
</div>

upspll_simpang_php5/resources/views/schedule_simpangs/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Schedule Simpangs</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('scheduleSimpangs.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('schedule_simpangs.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

upspll_simpang_php5/resources/views/schedule_simpangs/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Schedule Simpang
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('schedule_simpangs.show_fields')
                    <a href="{!! route('scheduleSimpangs.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

upspll_simpang_php5/resources/views/schedule_simpangs/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $scheduleSimpang->id !!}</p>
</div>

<!-- Nama Lokasi Field -->
<div class="form-group">
    {!! Form::label('nama_lokasi', 'Nama Lokasi:') !!}
    <p>{!! $scheduleSimpang->nama_lokasi !!}</p>
</div>

<!-- Nomor Plan Field -->
<div class="form-group">
    {!! Form::label('nomor_plan', 'Nomor Plan:') !!}
    <p>{!! $scheduleSimpang->nomor_plan !!}</p>
</div>

<!-- Ct Field -->
<div class="form-group">
    {!! Form::label('ct', 'Ct:') !!}
    <p>{!! $scheduleSimpang->ct !!}</p>
</div>

<!-- Time Field -->
<div class="form-group">
    {!! Form::label('time', 'Time:') !!}
    <p>{!! $scheduleSimpang->time !!}</p>
</div>

<!-- Days Field -->
<div class="form-group">
    {!! Form::label('days', 'Days:') !!}
    <p>{!! $scheduleSimpang->days !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $scheduleSimpang->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $scheduleSimpang->updated_at !!}</p>
</div>

<!-- Deleted At Field -->
<div class="form-group">
    {!! Form::label('deleted_at', 'Deleted At:') !!}
    <p>{!! $scheduleSimpang->deleted_at !!}</p>
</div>

upspll_simpang_php5/resources/views/schedule_simpangs/table.blade.php
<table class="table table-responsive" id="scheduleSimpangs-table">
    <thead>
        <tr>
            <th>Nama Lokasi</th>
        <th>Nomor Plan</th>
        <th>Ct</th>
        <th>Time</th>
        <th>Days</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($scheduleSimpangs as $scheduleSimpang)
        <tr>
            <td>{!! $scheduleSimpang->nama_lokasi !!}</td>
            <td>{!! $scheduleSimpang->nomor_plan !!}</td>
            <td>{!! $scheduleSimpang->ct !!}</td>
            <td>{!! $scheduleSimpang->time !!}</td>
            <td>{!! $scheduleSimpang->days !!}</td>
            <td>
                {!! Form::open(['route' => ['scheduleSimpangs.destroy', $scheduleSimpang->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('scheduleSimpangs.show', [$scheduleSimpang->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('scheduleSimpangs.edit', [$scheduleSimpang->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>