upspll_inventaris/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {
    return view('auth/login');
});

Route::get('/', 'ms_lokasiController@index')->middleware('admin');
    
Route::get('/home', 'ms_lokasiController@index')->middleware('admin');
Route::get('/maps', 'ms_lokasiController@maps')->middleware('admin');
// Route::get('/lokasi', 'lokasiController@index');
// Route::get('/lokasi/cetak_pdf', 'lokasiController@cetak_pdf');

Route::get('upspll_inventaris/detailSimpang/cetak_pdf/{id}', 'detail_simpangController@cetak_pdf')->middleware('admin');

Route::get('upspll_inventaris/ms_lokasi/cetak_pdf_lokasiatcs', 'ms_lokasiController@cetak_pdf_lokasiatcs')->middleware('admin');

Route::get('upspll_inventaris/ms_lokasi/cetak_pdf_lokasinonatcs', 'ms_lokasiController@cetak_pdf_lokasinonatcs')->middleware('admin');

Route::resource('msLokasis', 'ms_lokasiController', ['middleware' => ['admin']]);

Route::resource('detailSimpangs', 'detail_simpangController', ['middleware' => ['admin']]);

Route::resource('planSimpangs', 'plan_simpangController', ['middleware' => ['admin']]);

Route::get('upspll_inventaris/plansimpangadd/{id}', 'plan_simpangController@addsimpang')->middleware('admin');

Route::resource('scheduleSimpangs', 'schedule_simpangController', ['middleware' => ['admin']]);

Route::get('upspll_inventaris/schedulesimpangadd/{id}', 'schedule_simpangController@addsimpang')->middleware('admin');

Route::get('upspll_inventaris/detail_simpangController/fetch_data', 'detail_simpangController@fetch_data')->middleware('admin');

Route::post('/detail_simpangController/update_data', 'detail_simpangController@update_data')->name('detail_simpangController.update_data');
Route::post('/detail_simpangController/delete_data', 'detail_simpangController@delete_data')->name('detail_simpangController.delete_data');


Route::get('upspll_inventaris/detail_simpangController/fetch_data2', 'detail_simpangController@fetch_data2')->middleware('admin');

Route::post('/detail_simpangController/update_data2', 'detail_simpangController@update_data2')->name('detail_simpangController.update_data2');
Route::post('/detail_simpangController/delete_data2', 'detail_simpangController@delete_data2')->name('detail_simpangController.delete_data2');



Route::resource('masterTiangs', 'master_tiangController', ['middleware' => ['admin']]);
Route::resource('masterLampus', 'master_lampuController', ['middleware' => ['admin']]);

Route::resource('detailTiangs', 'detail_tiangController', ['middleware' => ['admin']]);

Route::resource('detailLampus', 'detail_lampuController', ['middleware' => ['admin']]);


Route::get('/', 'HomeController@dashboard')->middleware('teknisi');


Route::get('/detail/{id}', 'HomeController@detail')->middleware('teknisi');
Route::get('/detailSimpang/cari','HomeController@cari')->middleware('teknisi');

upspll_inventaris/app/Models/ms_lokasi.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class ms_lokasi
 * @package App\Models
 * @version January 10, 2020, 12:57 am UTC
 *
 * @property integer id_lokasi
 * @property string nomor_lokasi
 * @property string nama_lokasi
 */
class ms_lokasi extends Model
{
    

    public $table = 'ms_lokasi';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';

    public $fillable = [
        'nomor_lokasi',
        'nama_lokasi',
        'kategori'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'nomor_lokasi' => 'string',
        'nama_lokasi' => 'string',
        'kategori' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'nama_lokasi' => 'required'
    ];

    
}

upspll_inventaris/app/Http/Controllers/ms_lokasiController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Createms_lokasiRequest;
use App\Http\Requests\Updatems_lokasiRequest;
use App\Repositories\ms_lokasiRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;
use App\Models\ms_lokasi;
use App;
use PDF;

class ms_lokasiController extends AppBaseController
{
    /** @var  ms_lokasiRepository */
    private $msLokasiRepository;

    public function __construct(ms_lokasiRepository $msLokasiRepo)
    {
        $this->msLokasiRepository = $msLokasiRepo;
    }

    /**
     * Display a listing of the ms_lokasi.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->msLokasiRepository->pushCriteria(new RequestCriteria($request));
        $msLokasis = $this->msLokasiRepository->all();

        return view('ms_lokasis.index')
            ->with('msLokasis', $msLokasis);
    }

    public function maps(Request $request)
    {
        $this->msLokasiRepository->pushCriteria(new RequestCriteria($request));
        $msLokasis = $this->msLokasiRepository->all();

        return view('ms_lokasis.maps')
            ->with('msLokasis', $msLokasis);
    }

    public function cetak_pdf_lokasiatcs()
    {
        // $pdf = App::make('dompdf.wrapper');
        // $pdf->loadHTML('<h1>Test</h1>');
        // return $pdf->stream();
        $msLokasi = \App\Models\ms_lokasi::where('kategori','=','ATCS')->get();
         // dd($schedule);

        $pdf = PDF::loadview('ms_lokasis.showpdf', ['msLokasi'=> $msLokasi])->setPaper('legal', 'portrait');
        
    	return $pdf->download('daftar-lokasi-simpang-atcs.pdf');
    }

    public function cetak_pdf_lokasinonatcs()
    {
        // $pdf = App::make('dompdf.wrapper');
        // $pdf->loadHTML('<h1>Test</h1>');
        // return $pdf->stream();
        $msLokasi = \App\Models\ms_lokasi::where('kategori','=','NON ATCS')->get();
         // dd($schedule);

        $pdf = PDF::loadview('ms_lokasis.showpdf2', ['msLokasi'=> $msLokasi])->setPaper('legal', 'portrait');
        
    	return $pdf->download('daftar-lokasi-simpang-non-atcs.pdf');
    }


    /**
     * Show the form for creating a new ms_lokasi.
     *
     * @return Response
     */
    public function create()
    {
        return view('ms_lokasis.create');
    }

    /**
     * Store a newly created ms_lokasi in storage.
     *
     * @param Createms_lokasiRequest $request
     *
     * @return Response
     */
    public function store(Createms_lokasiRequest $request)
    {
        $input = $request->all();

        $msLokasi = $this->msLokasiRepository->create($input);

        Flash::success('Ms Lokasi saved successfully.');

        return redirect(route('msLokasis.index'));
    }

    /**
     * Display the specified ms_lokasi.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $msLokasi = $this->msLokasiRepository->findWithoutFail($id);

        if (empty($msLokasi)) {
            Flash::error('Ms Lokasi not found');

            return redirect(route('msLokasis.index'));
        }

        return view('ms_lokasis.show')->with('msLokasi', $msLokasi);
    }

    /**
     * Show the form for editing the specified ms_lokasi.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $msLokasi = $this->msLokasiRepository->findWithoutFail($id);

        if (empty($msLokasi)) {
            Flash::error('Ms Lokasi not found');

            return redirect(route('msLokasis.index'));
        }

        return view('ms_lokasis.edit')->with('msLokasi', $msLokasi);
    }

    /**
     * Update the specified ms_lokasi in storage.
     *
     * @param  int              $id
     * @param Updatems_lokasiRequest $request
     *
     * @return Response
     */
    public function update($id, Updatems_lokasiRequest $request)
    {
        $msLokasi = $this->msLokasiRepository->findWithoutFail($id);

        if (empty($msLokasi)) {
            Flash::error('Ms Lokasi not found');

            return redirect(route('msLokasis.index'));
        }

        $msLokasi = $this->msLokasiRepository->update($request->all(), $id);

        Flash::success('Ms Lokasi updated successfully.');

        return redirect(route('msLokasis.index'));
    }

    /**
     * Remove the specified ms_lokasi from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $msLokasi = $this->msLokasiRepository->findWithoutFail($id);

        if (empty($msLokasi)) {
            Flash::error('Ms Lokasi not found');

            return redirect(route('msLokasis.index'));
        }

        $this->msLokasiRepository->delete($id);

        Flash::success('Ms Lokasi deleted successfully.');

        return redirect(route('msLokasis.index'));
    }
}

upspll_inventaris/resources/views/ms_lokasis/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
           Master Lokasi
        </h1>
    </section>
    <div class="content">
    @if(auth::user()->role=='Admin')
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'msLokasis.store']) !!}

                        @include('ms_lokasis.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
        @endif
        @if(auth::user()->role=='Operator')
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'msLokasis.store']) !!}

                        @include('ms_lokasis.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
        @endif
        @if(auth::user()->role=='Teknisi')
        <h1>
        404 Akses ditolak
        </h1>
        @endif
    </div>
@endsection

upspll_inventaris/resources/views/ms_lokasis/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Master Lokasi
        </h1>
   </section>
   <div class="content">
   
   @if(auth::user()->role=='Admin')
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($msLokasi, ['route' => ['msLokasis.update', $msLokasi->id], 'method' => 'patch']) !!}

                        @include('ms_lokasis.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
       @endif
       @if(auth::user()->role=='Operator')
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($msLokasi, ['route' => ['msLokasis.update', $msLokasi->id], 'method' => 'patch']) !!}

                        @include('ms_lokasis.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
       @endif
       @if(auth::user()->role=='Teknisi')
       <h1>
            404 Akses ditolak
        </h1>
       @endif
   </div>
@endsection

upspll_inventaris/resources/views/ms_lokasis/fields.blade.php
<div class="form-group col-sm-6">
    {!! Form::label('kategori', 'Kategori:') !!}
    <select class="form-control" name="kategori"  value="{{ old('controller') }}" >
    <option value="">----pilih kategori----</option>
    <option value="ATCS">ATCS</option>
    <option value="NON ATCS">NON ATCS</option>
    </select>
</div>


<!-- Nomor Lokasi Field -->
<div class="form-group col-sm-6">
    {!! Form::label('nomor_lokasi', 'SID:') !!}
    {!! Form::text('nomor_lokasi', null, ['class' => 'form-control']) !!}
</div>

<!-- Nama Lokasi Field -->
<div class="form-group col-sm-6">
    {!! Form::label('nama_lokasi', 'Nama Lokasi:') !!}
    {!! Form::text('nama_lokasi', null, ['class' => 'form-control']) !!}
</div>


<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'uk-button uk-button-primary uk-button uk-button-small']) !!}
    <a href="{!! route('msLokasis.index') !!}" class="uk-button uk-button-default uk-button-small" >Cancel</a>
</div>

upspll_inventaris/resources/views/ms_lokasis/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Master Lokasi</h1>
        <h1 class="pull-right">  
            @if(auth::user()->role == 'Admin')
                <a class="uk-button uk-button-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('msLokasis.create') !!}">Add New</a>
            @endif
            @if(auth::user()->role=='Operator')
                <a class="uk-button uk-button-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('msLokasis.create') !!}">Add New</a>
            @endif
            @if(auth::user()->role=='teknisi')
                <a class="uk-button uk-button-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('msLokasis.create') !!}" disabled>Add New</a>
            @endif
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>
        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
            <a href="{{url('upspll_inventaris/ms_lokasi/cetak_pdf_lokasiatcs')}}" class="uk-button uk-button-primary uk-button-small" target="_blank" style="margin-bottom:20px;">CETAK PDF LOKASI ATCS</a>
            <a href="{{url('upspll_inventaris/ms_lokasi/cetak_pdf_lokasinonatcs')}}" class="uk-button uk-button-primary uk-button-small" target="_blank" style="margin-bottom:20px;">CETAK PDF LOKASI NON ATCS</a>
           
                    @include('ms_lokasis.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

upspll_inventaris/resources/views/ms_lokasis/maps.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Maps Lokasi</h1>
       
    </section>
    <hr>
    <div class="content"style="padding-right:10px;">
    <div id="map" style="width:100%;height:500px;">
    
    </div>
    </div>
@endsection

upspll_inventaris/resources/views/ms_lokasis/ms_lokasi.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>UP SPLL DISHUB</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <style>
      table {
  border-collapse: collapse;
}
 th {
  background: #ccc;
}

th, td {
  border: 1px solid #ccc;
  padding: 8px;
}

tr:nth-child(even) {
  background: #efefef;
}

tr:hover {
  background: #d1d1d1;
}
    </style>
</head>

<body class="sidebar-mini">
<div class="table-responsive" style="width:100%;">
<center>
<h2>DAFTAR LOKASI SIMPANG UPSPLL DISHUB DKI JAKARTA</h2>
<table id="table" class="table">
<thead>
            <tr>
                <th>Nomor</th>
        <th>SID</th>
        <th>Nama Lokasi</th>
            </tr>
        </thead>
        <tbody> 
        @foreach($msLokasis as $msLokasi)
            <tr>
                <td>{{ $msLokasi->id }}</td>
            <td>{{ $msLokasi->nomor_lokasi }}</td>
            <td>{{ $msLokasi->nama_lokasi }}</td>
          
            </tr>
        @endforeach
        </tbody>
</table>
</center>
</div>


</body>
</html>

upspll_inventaris/resources/views/ms_lokasis/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Ms Lokasi
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                   @include('ms_lokasis.show_fields')
                    <a href="{!! route('msLokasis.index') !!}" class="uk-button uk-button-default uk-button-small">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

upspll_inventaris/resources/views/ms_lokasis/show_fields.blade.php
<!-- Nomor Lokasi Field -->
<div class="form-group">
    {!! Form::label('nomor_lokasi', 'SID:') !!}
    <p>{!! $msLokasi->nomor_lokasi !!}</p>
</div>

<!-- Nama Lokasi Field -->
<div class="form-group">
    {!! Form::label('nama_lokasi', 'Nama Lokasi:') !!}
    <p>{!! $msLokasi->nama_lokasi !!}</p>
</div>

<!-- Nama Lokasi Field -->
<div class="form-group">
    {!! Form::label('kategori', 'Kategori:') !!}
    <p>{!! $msLokasi->kategori !!}</p>
</div>

upspll_inventaris/resources/views/ms_lokasis/showpdf.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
           table {
  border-collapse: collapse;
}
 th {
  background: #ccc;
}

th, td {
  border: 1px solid #ccc;
  padding: 8px;
}

tr:nth-child(even) {
  background: #efefef;
}

tr:hover {
  background: #d1d1d1;
}
    </style>
</head>

<body>

    <h2>Daftar Lokasi Simpang ATCS</h2>
  
    
    <table>
        <thead>
            <tr>
        <th>SID</th>
        <th>Nama Lokasi</th>
        
            </tr>
        </thead>
        <tbody>
        @foreach($msLokasi as $msLokasis)
            <tr>
                <td>{!! $msLokasis->nomor_lokasi !!}</td>
            <td>{!! $msLokasis->nama_lokasi !!}</td>
            
           </tr>
           
    @endforeach
        </tbody>
    </table>
</body>

</html>

upspll_inventaris/resources/views/ms_lokasis/showpdf2.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
           table {
  border-collapse: collapse;
}
 th {
  background: #ccc;
}

th, td {
  border: 1px solid #ccc;
  padding: 8px;
}

tr:nth-child(even) {
  background: #efefef;
}

tr:hover {
  background: #d1d1d1;
}
    </style>
</head>

<body>

    <h2>Daftar Lokasi Simpang NON ATCS</h2>
  
    
    <table>
        <thead>
            <tr>
        <th>Nama Lokasi</th>
        
            </tr>
        </thead>
        <tbody>
        @foreach($msLokasi as $msLokasis)
            <tr>
            <td>{!! $msLokasis->nama_lokasi !!}</td>
            
           </tr>
           
    @endforeach
        </tbody>
    </table>
</body>

</html>

upspll_inventaris/resources/views/ms_lokasis/table.blade.php
<div class="table-responsive" style="width:100%;">
<table id="table" class="uk-table uk-table-hover uk-table-striped">
<thead>
            <tr>
                <th>Nomor</th>
        <th>SID</th>
        <th>Nama Lokasi</th>
        <th>kategori</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody> 
        @foreach($msLokasis as $msLokasi)
            <tr>
                <td>{{ $msLokasi->id }}</td>
            <td>{{ $msLokasi->nomor_lokasi }}</td>
            <td>{{ $msLokasi->nama_lokasi }}</td>
            <td>{{ $msLokasi->kategori }}</td>
                <td>
                    {!! Form::open(['route' => ['msLokasis.destroy', $msLokasi->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('msLokasis.show', [$msLokasi->id]) }}" class='uk-button uk-button-default '><i class="glyphicon glyphicon-eye-open"></i></a>
                        @if(auth::user()->role=='Admin')
                        <a href="{{ route('msLokasis.edit', [$msLokasi->id]) }}" class='uk-button uk-button-primary ' ><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'uk-button uk-button-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                        @endif
                        @if(auth::user()->role=='Operator')
                        <a href="{{ route('msLokasis.edit', [$msLokasi->id]) }}" class='uk-button uk-button-primary ' ><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'uk-button uk-button-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                        @endif
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
</table>
</div>