upspll_inventaris/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {
    return view('auth/login');
});

Route::get('/', 'ms_lokasiController@index')->middleware('admin');
    
Route::get('/home', 'ms_lokasiController@index')->middleware('admin');
Route::get('/maps', 'ms_lokasiController@maps')->middleware('admin');
// Route::get('/lokasi', 'lokasiController@index');
// Route::get('/lokasi/cetak_pdf', 'lokasiController@cetak_pdf');

Route::get('upspll_inventaris/detailSimpang/cetak_pdf/{id}', 'detail_simpangController@cetak_pdf')->middleware('admin');

Route::get('upspll_inventaris/ms_lokasi/cetak_pdf_lokasiatcs', 'ms_lokasiController@cetak_pdf_lokasiatcs')->middleware('admin');

Route::get('upspll_inventaris/ms_lokasi/cetak_pdf_lokasinonatcs', 'ms_lokasiController@cetak_pdf_lokasinonatcs')->middleware('admin');

Route::resource('msLokasis', 'ms_lokasiController', ['middleware' => ['admin']]);

Route::resource('detailSimpangs', 'detail_simpangController', ['middleware' => ['admin']]);

Route::resource('planSimpangs', 'plan_simpangController', ['middleware' => ['admin']]);

Route::get('upspll_inventaris/plansimpangadd/{id}', 'plan_simpangController@addsimpang')->middleware('admin');

Route::resource('scheduleSimpangs', 'schedule_simpangController', ['middleware' => ['admin']]);

Route::get('upspll_inventaris/schedulesimpangadd/{id}', 'schedule_simpangController@addsimpang')->middleware('admin');

Route::get('upspll_inventaris/detail_simpangController/fetch_data', 'detail_simpangController@fetch_data')->middleware('admin');

Route::post('/detail_simpangController/update_data', 'detail_simpangController@update_data')->name('detail_simpangController.update_data');
Route::post('/detail_simpangController/delete_data', 'detail_simpangController@delete_data')->name('detail_simpangController.delete_data');


Route::get('upspll_inventaris/detail_simpangController/fetch_data2', 'detail_simpangController@fetch_data2')->middleware('admin');

Route::post('/detail_simpangController/update_data2', 'detail_simpangController@update_data2')->name('detail_simpangController.update_data2');
Route::post('/detail_simpangController/delete_data2', 'detail_simpangController@delete_data2')->name('detail_simpangController.delete_data2');



Route::resource('masterTiangs', 'master_tiangController', ['middleware' => ['admin']]);
Route::resource('masterLampus', 'master_lampuController', ['middleware' => ['admin']]);

Route::resource('detailTiangs', 'detail_tiangController', ['middleware' => ['admin']]);

Route::resource('detailLampus', 'detail_lampuController', ['middleware' => ['admin']]);


Route::get('/', 'HomeController@dashboard')->middleware('teknisi');


Route::get('/detail/{id}', 'HomeController@detail')->middleware('teknisi');
Route::get('/detailSimpang/cari','HomeController@cari')->middleware('teknisi');

upspll_inventaris/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>UP SPLL DISHUB</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Theme style -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/css/AdminLTE.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/css/skins/_all-skins.min.css">

    <!-- iCheck -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/skins/square/_all.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.min.css">

    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/css/bootstrap-datetimepicker.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">
    <!-- UIkit CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/css/uikit.min.css" />
    @yield('css')
</head>

<body class="sidebar-mini">  @if (!Auth::guest())
    <div class="wrapper">
        <!-- Main Header -->
        <header class="main-header"  style="background:#2C166E !important">

            <!-- Logo -->
            <a href="#" class="logo">
                <b style="color:white !important">UPSPLL SIMPANG</b>
            </a>

            <!-- Header Navbar -->
            <nav class="navbar navbar-static-top" role="navigation" style="background:#2C166E !important">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button" style="color:white !important">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account Menu -->
                        <li class="dropdown user user-menu">
                            <!-- Menu Toggle Button -->
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <!-- The user image in the navbar-->
                                <img src="http://infyom.com/images/logo/blue_logo_150x150.jpg" class="user-image"
                                    alt="User Image" />
                                <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                <span class="hidden-xs" style="color:white !important">{{ Auth::user()->name }}</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- The user image in the menu -->
                                <li class="user-header">
                                    <img src="http://infyom.com/images/logo/blue_logo_150x150.jpg" class="img-circle"
                                        alt="User Image" />
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <!-- <div class="pull-left">
                                        <a href="#" class="btn btn-default btn-flat">Profile</a>
                                    </div> -->
                                    <div class="pull-right">
                                        <a href="{{ url('/logout') }}" class="btn btn-default btn-flat"
                                            onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                            Sign out
                                        </a>
                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST"
                                            style="display: none;">
                                            @csrf
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        </form>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>

        <!-- Left side column. contains the logo and sidebar -->
        @include('layouts.sidebar')
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            @yield('content')
        </div>

        <!-- Main Footer -->
        <footer class="main-footer" style="max-height: 100px;text-align: center">
            <strong>Copyright © 2020 <a href="http://upspll.jakarta.go.id/">UPSPLL DISHUB DKI JAKARTA</a>.</strong> All rights reserved.
        </footer>

    </div>
    @else
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    InfyOm Generator
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    <li><a href="{{ url('/home') }}">Home</a></li>
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    <li><a href="{{ url('/login') }}">Login</a></li>
                    <li><a href="{{ url('/register') }}">Register</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div id="page-content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    @yield('content')
                </div>
            </div>
        </div>
    </div>
    @endif

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js">
    </script>
<script>
        $(document).ready(function () {
            $('#table').DataTable();
        });
      
        $(document).ready(function () {
            $('#tableps').DataTable();
        });
      
        $(document).ready(function () {
            $('#tabless').DataTable();
        });

        $(document).ready(function () {
            $('#tabless').DataTable();
        });

        
        $('#tableps, #tabless').dataTable( {
  "lengthMenu": [ 5,10,25,50,75 ]
} );
// var ctx = document.getElementById('myChart').getContext('2d');
// var chart = new Chart(ctx, {
//     type: 'bar',
//         data: [20, 10]

   
// options: {
//         scales: {
//             xAxes: [{
//                 stacked: true
//             }],
//             yAxes: [{
//                 stacked: true
//             }]
//         }
//     }
// });
    </script>

    <!-- jQuery 3.1.1 -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.1/moment.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js">
    </script>
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/js/adminlte.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/icheck.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/select2.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCN06xnwrMwHdaYbcHJXqiFlZxwWJ-_8p8&callback=lokasimaps"
    async defer></script>
    <script type="text/javascript">
        function lokasimaps(){
            var latLng = new google.maps.LatLng(-6.21, 106.85),
            option = {
                center:latLng,
                zoom:12
            },
            map = new google.maps.Map(document.getElementById('map'), option);
        }
    </script>
<!-- UIkit JS -->
<script src="https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit-icons.min.js"></script>
<!-- chartJS -->
    @yield('scripts')
</body>
</html>

upspll_inventaris/resources/views/layouts/datatables_css.blade.php
<!-- DataTable Bootstrap -->
<link href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.2.2/css/buttons.bootstrap.min.css">

upspll_inventaris/resources/views/layouts/datatables_js.blade.php
<!-- Datatables -->
<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.colVis.min.js"></script>
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>

upspll_inventaris/resources/views/layouts/menu.blade.php
<li class="{{ Request::is('msLokasis*') ? 'active' : '' }}">
    <a href="{{ route('msLokasis.index') }}" class="uk-text-emphasis uk-text-bold"><i class="fa fa-edit"></i><span>Master Lokasi</span></a>
</li>

<li class="{{ Request::is('detailSimpangs*') ? 'active' : '' }}">
    <a href="{{ route('detailSimpangs.index') }}" class="uk-text-emphasis uk-text-bold"><i class="fa fa-edit"></i><span>Detail Simpang</span></a>
</li>

<!-- <li class="{{ Request::is('planSimpangs*') ? 'active' : '' }}">
    <a href="{{ route('planSimpangs.index') }}" class="uk-text-emphasis uk-text-bold"><i class="fa fa-edit"></i><span>Plan Simpang</span></a>
</li>

<li class="{{ Request::is('scheduleSimpangs*') ? 'active' : '' }}">
    <a href="{!! route('scheduleSimpangs.index') !!}" class="uk-text-emphasis uk-text-bold"><i class="fa fa-edit"></i><span>Schedule Simpangs</span></a>
</li>
 -->
<li class="{{ Request::is('masterTiangs*') ? 'active' : '' }}">
    <a href="{!! route('masterTiangs.index') !!}" class="uk-text-emphasis uk-text-bold"><i class="fa fa-edit"></i><span>Master Tiang</span></a>
</li><li class="{{ Request::is('masterLampus*') ? 'active' : '' }}">
    <a href="{!! route('masterLampus.index') !!}" class="uk-text-emphasis uk-text-bold"><i class="fa fa-edit"></i><span>Master Lampu</span></a>
</li>
<!-- 
<li class="{{ Request::is('detailTiangs*') ? 'active' : '' }}">
    <a href="{!! route('detailTiangs.index') !!}"><i class="fa fa-edit"></i><span>Detail Tiangs</span></a>
</li>
 -->
<!-- <li class="{{ Request::is('detailLampus*') ? 'active' : '' }}">
    <a href="{!! route('detailLampus.index') !!}"><i class="fa fa-edit"></i><span>Detail Lampus</span></a>
</li>
 -->

upspll_inventaris/resources/views/layouts/sidebar.blade.php
<aside class="main-sidebar" id="sidebar-wrapper">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar user panel (optional) -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="http://infyom.com/images/logo/blue_logo_150x150.jpg" class="img-circle"
                     alt="User Image"/>
            </div>
            <div class="pull-left info">
                @if (Auth::guest())
                <p>InfyOm</p>
                @else
                    <p>{{ Auth::user()->name}}</p>
                @endif
                <!-- Status -->
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>

        <!-- Sidebar Menu -->

        <ul class="sidebar-menu" data-widget="tree">
            @include('layouts.menu')
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>